apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc

spec:
  replicas: 2
  selector:
    myname: vivek

  template:   
    metadata:
      labels:      
        myname: vivek
    spec:
      containers:
        - name: c1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo hello rc; sleep 5; done"]       
