kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplicationcontroller

spec:
 replicas: 2
 selector:
   myname: vivek
 
 template:
   metadata:
     labels:
       myname: vivek
   spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello Vivek; sleep 5 ; done"]

