kind: ReplicaSet
apiVersion: app/v1
metadata:
  name: myreplicaset

spec:
  repicas: 2
  selector: 
    matchLabels:
      myname: vivek

  template:
    metadata:
      labels:
        myname: vivek
     spec:
       containers:
         - name: c00
           image: ubuntu
           command: ["/bin/bash", "-c", "while true; do echo hello-vivek; sleep 5 ; done"]
